[Step1] 화면 응답 개선하기 리뷰요청 드립니다.
next-step/infra-subway-stable pull request #3
Opened 2022-08-31 15:19 UTC by ksundong

시나리오가 정적 리소스의 서빙 및 캐싱에 의존하는 시나리오여서 nginx 튜닝만으로도 유의미한 차이가 발생해서 리뷰요청드립니다~

2022-09-01 08:15 UTC, brainbackdoor requested changes
1단계 미션 진행하느라 고생하셨어요~ 👍🏻 
몇가지 확인할 부분이 있어 피드백 남겨두었어요~
좋은 하루 보내요~

2022-09-01 08:15 UTC, brainbackdoor commented on README.md
> +  - ![aws-dashboard](./test_result/nginx_tuning/stress/aws-dashboard.png)
https://github.com/ksundong/infra-subway-monitoring/blob/88125b3b424df2dbc3d4229d061a543586edfff2/README.md

성능 개선 전보다 응답시간이 높아졌는데요.
혹시 어떤 설정들을 하고 테스트를 진행하셨을까요?

2022-09-01 08:15 UTC, brainbackdoor commented on src/test/k6/login_success/load.js
> +    http_req_duration: ['p(99)<400'], // 99% of requests must complete below 400ms
목표 응답시간이 100ms 에서 400ms로 변경되었네요..?

2022-09-01 08:15 UTC, brainbackdoor commented on src/main/java/nextstep/subway/common/CacheConfig.java
> +    return redisCacheManager;
데이터 캐시는 어디에 추가하셨을까요?

2022-09-01 08:17 UTC, ksundong commented on src/test/k6/login_success/load.js
> +    http_req_duration: ['p(99)<400'], // 99% of requests must complete below 400ms
latency의 2배라고 하신 피드백을 반영한 부분입니다!
2회 요청을 보내므로 400ms로 설정했습니다!

2022-09-01 08:18 UTC, ksundong commented on src/main/java/nextstep/subway/common/CacheConfig.java
> +    return redisCacheManager;
캐싱은 설정만 추가하고 적용하진 않았습니다~

2022-09-01 15:30 UTC, ksundong commented on README.md
> +  - ![aws-dashboard](./test_result/nginx_tuning/stress/aws-dashboard.png)
지표상으로 봤을 때 순간적으로 Maximum 값이 튀는 부분은 있었지만 avg 값이 낮아진 것으로 확인되었습니다.
설정은 같으나, 제가 테스트한 네트워크 환경이 달라서 조금 달라진 부분이 있을것으로 생각됩니다~

2022-09-02 13:06 UTC, brainbackdoor approved these changes
넵~ Comment 확인헀어요~
이번 단계는 여기서 머지할게요~

2022-09-02 13:06 UTC, merged